Preprocess:
    normalization_method: 'max'

Train:
    SelfSupVis:
        num_clusters: [3, 4, 5]
        projection_dim: [12, 12, 12]

Model:
    differential_input: False 
    encoder_type: 'LSTM'
    decoder_type: 'LSTM'